export type ParkId = 
  | 'MURCHISON'
  | 'BWINDI'
  | 'QUEEN_ELIZABETH'
  | 'KIBALE'
  | 'MGAHINGA'
  | 'KIDEPO'
  | 'LAKE_MBURO'
  | 'MT_ELGON'
  | 'RWENZORI'
  | 'SEMULIKI'
  | 'ZIWA'
  | 'BUSIKA'
  | 'ENTEBBE'
  | 'LAKE_BUNYONYI'
  | 'JINJA';
