/**
 * Pricing Catalog Audit Script
 * Analyzes the pricingCatalog collection and generates a comprehensive audit report
 * Run with: node scripts/auditCatalog.mjs
 */

import admin from 'firebase-admin';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Firebase Admin
admin.initializeApp({
  projectId: 'discover-africa-quotation-app'
});

const db = admin.firestore();

// Helper function to detect if ID is auto-generated (Firestore style)
function isAutoGeneratedId(id) {
  // Firestore auto-generated IDs are 20 characters, alphanumeric
  // Custom IDs typically have underscores, hyphens, or are shorter/longer
  const firestoreIdPattern = /^[a-zA-Z0-9]{20}$/;
  return firestoreIdPattern.test(id);
}

// Helper function to check if SKU is populated
function hasValidSku(sku) {
  return sku && sku.trim().length > 0;
}

async function auditCatalog() {
  console.log('🔍 Starting Pricing Catalog Audit...\n');
  
  try {
    // Fetch all items from pricingCatalog
    const snapshot = await db.collection('pricingCatalog').get();
    
    console.log(`📦 Retrieved ${snapshot.size} documents from pricingCatalog\n`);

    // Initialize audit data structures
    const auditData = {
      metadata: {
        totalItems: snapshot.size,
        auditDate: new Date().toISOString(),
        collection: 'pricingCatalog'
      },
      idAnalysis: {
        autoGenerated: 0,
        customReadable: 0
      },
      skuAnalysis: {
        withSku: 0,
        missingSku: 0,
        emptySku: 0
      },
      categoryBreakdown: {},
      items: []
    };

    // Process each document
    snapshot.forEach(doc => {
      const data = doc.data();
      const docId = doc.id;
      
      // Analyze ID format
      const isAutoGen = isAutoGeneratedId(docId);
      if (isAutoGen) {
        auditData.idAnalysis.autoGenerated++;
      } else {
        auditData.idAnalysis.customReadable++;
      }

      // Analyze SKU
      const hasSku = hasValidSku(data.sku);
      if (hasSku) {
        auditData.skuAnalysis.withSku++;
      } else if (data.sku === '' || data.sku === null || data.sku === undefined) {
        if (data.sku === '') {
          auditData.skuAnalysis.emptySku++;
        } else {
          auditData.skuAnalysis.missingSku++;
        }
      }

      // Category breakdown
      const category = data.category || 'Uncategorized';
      if (!auditData.categoryBreakdown[category]) {
        auditData.categoryBreakdown[category] = 0;
      }
      auditData.categoryBreakdown[category]++;

      // Add item to full list
      auditData.items.push({
        documentId: docId,
        itemName: data.itemName || '',
        category: category,
        parkId: data.parkId || null,
        sku: data.sku || null,
        hasSku: hasSku,
        isAutoGeneratedId: isAutoGen,
        appliesTo: data.appliesTo || 'Unknown',
        active: data.active !== false,
        basePrice: data.basePrice || 0,
        costType: data.costType || ''
      });
    });

    // Sort items by category, then by itemName
    auditData.items.sort((a, b) => {
      if (a.category !== b.category) {
        return a.category.localeCompare(b.category);
      }
      return a.itemName.localeCompare(b.itemName);
    });

    // Save audit to JSON file
    const outputPath = path.join(__dirname, '..', 'catalog_audit.json');
    fs.writeFileSync(outputPath, JSON.stringify(auditData, null, 2));
    
    console.log('✅ Audit complete! Saved to: catalog_audit.json\n');

    // Print summary table
    console.log('═══════════════════════════════════════════════════════════');
    console.log('                  PRICING CATALOG AUDIT SUMMARY');
    console.log('═══════════════════════════════════════════════════════════\n');

    console.log('📊 OVERVIEW');
    console.log('─────────────────────────────────────────────────────────');
    console.log(`Total Items:              ${auditData.metadata.totalItems}`);
    console.log(`Audit Date:               ${new Date(auditData.metadata.auditDate).toLocaleString()}`);
    console.log('');

    console.log('🆔 ID FORMAT ANALYSIS');
    console.log('─────────────────────────────────────────────────────────');
    console.log(`Auto-generated IDs:       ${auditData.idAnalysis.autoGenerated} (${((auditData.idAnalysis.autoGenerated / auditData.metadata.totalItems) * 100).toFixed(1)}%)`);
    console.log(`Custom/Readable IDs:      ${auditData.idAnalysis.customReadable} (${((auditData.idAnalysis.customReadable / auditData.metadata.totalItems) * 100).toFixed(1)}%)`);
    console.log('');

    console.log('🏷️  SKU ANALYSIS');
    console.log('─────────────────────────────────────────────────────────');
    console.log(`Items WITH SKU:           ${auditData.skuAnalysis.withSku} (${((auditData.skuAnalysis.withSku / auditData.metadata.totalItems) * 100).toFixed(1)}%)`);
    console.log(`Items MISSING SKU:        ${auditData.skuAnalysis.missingSku} (${((auditData.skuAnalysis.missingSku / auditData.metadata.totalItems) * 100).toFixed(1)}%)`);
    console.log(`Items with EMPTY SKU:     ${auditData.skuAnalysis.emptySku} (${((auditData.skuAnalysis.emptySku / auditData.metadata.totalItems) * 100).toFixed(1)}%)`);
    console.log(`Total needing SKU:        ${auditData.skuAnalysis.missingSku + auditData.skuAnalysis.emptySku}`);
    console.log('');

    console.log('📂 CATEGORY BREAKDOWN');
    console.log('─────────────────────────────────────────────────────────');
    
    // Sort categories by count (descending)
    const sortedCategories = Object.entries(auditData.categoryBreakdown)
      .sort((a, b) => b[1] - a[1]);
    
    sortedCategories.forEach(([category, count]) => {
      const percentage = ((count / auditData.metadata.totalItems) * 100).toFixed(1);
      const paddedCategory = category.padEnd(25);
      const paddedCount = count.toString().padStart(3);
      console.log(`${paddedCategory} ${paddedCount} (${percentage}%)`);
    });
    
    console.log('');
    console.log('═══════════════════════════════════════════════════════════\n');

    // Print items missing SKU
    const itemsNeedingSku = auditData.items.filter(item => !item.hasSku);
    
    if (itemsNeedingSku.length > 0) {
      console.log('⚠️  ITEMS MISSING SKU (Sample - first 20):');
      console.log('─────────────────────────────────────────────────────────');
      
      itemsNeedingSku.slice(0, 20).forEach(item => {
        const parkInfo = item.parkId ? ` [${item.parkId}]` : ' [Global]';
        console.log(`  • ${item.category.padEnd(15)} | ${item.itemName}${parkInfo}`);
        console.log(`    Doc ID: ${item.documentId}`);
      });
      
      if (itemsNeedingSku.length > 20) {
        console.log(`\n  ... and ${itemsNeedingSku.length - 20} more items`);
      }
      console.log('');
    }

    console.log('📄 Full audit details saved to: catalog_audit.json');
    console.log('');
    console.log('💡 NEXT STEPS:');
    console.log('   1. Review catalog_audit.json for complete item list');
    console.log('   2. Generate SKUs for all items (format: PARK_CATEGORY_NAME_###)');
    console.log('   3. Update Firestore with new SKUs');
    console.log('   4. Verify SKUs match between Quote App and Itinerary Builder');
    console.log('');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error during audit:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

// Run the audit
auditCatalog();
